[package]
name = "zeevonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_ws281x = "0.4.4"
serde = "1.0.152"
tungstenite = "0.18.0"
